project:
  name: Markment
  version: 0.0.2
  description: A markdown-based automatic documentation generator
  github_maintainer: gabrielfalcao
  github_url: http://github.com/gabrielfalcao/markment
  github_fork_url: https://github.com/gabrielfalcao/markment/archive/master.tar.gz
  github_maintainer_url: http://github.com/gabrielfalcao
  github_maintainer_gravatar: https://secure.gravatar.com/avatar/3fa0df5c54f5ac0f8652d992d7d24039?s=64
  tarball_download_url: https://github.com/gabrielfalcao/markment/archive/master.tar.gz


documentation:
  index: index.md
