project:
  name: "Markment"
  version: "0.2.12"
  github_maintainer: "gabrielfalcao"
  description: "A markdown-based automatic documentation generator"
  github_url: "http://github.com/gabrielfalcao/markment"
  tarball_download_url: https://github.com/gabrielfalcao/markment/archive/master.tar.gz
  logo_path: images/logo.png
  logo_inline_css: "display: block"
documentation:
  index: index.md
