project:
  name: Markment
  version: 0.2.1
  description: A markdown-based automatic documentation generator
  github_url: http://github.com/gabrielfalcao/markment
  tarball_download_url: https://github.com/gabrielfalcao/markment/archive/master.tar.gz

documentation:
  index: index.md
